---
- name: Gather Facts from Cisco Devices
  hosts: all
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: ios
    report_format: txt
  collections:
    - cisco.ios

  tasks:
    - name: Ping for reachability
      command: ping -c2 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: true
      check_mode: false

    - name: Import serial_report role
      import_role:
        name: serial_report
