---
# tasks file for serial_report

- name: Gather device information
  ios_facts:
    gather_subset: min
  register: ios_facts
  when: ping_result.rc == 0

# - debug: var=ansible_net_stacked_serialnums
  when: ansible_net_stacked_serialnums is defined

# - debug: var=ansible_net_serialnums
  when: ansible_net_stacked_serialnums is not defined

- name: Generate txt report file
  local_action: template src=templates/txt_report_template.j2 dest=/tmp/Cisco_Serial_Report.txt
  when: report_format == 'txt'
  run_once: true
  check_mode: false

- name: Generate csv report file
  template:
    src: templates/csv_report_template.j2
    dest: /tmp/Cisco_Serial_Report.csv
  when: report_format == 'csv'
  delegate_to: localhost
  run_once: true
  check_mode: false

- name: Email Serial Number Report
  mail:
    from: "{{ from_email }}"
    to: "{{ email_address }}"
    subject: Serial Number Report for "{{ lookup('pipe','date +%Y-%m-%d') }}"
    subtype: html
    attach: /tmp/Cisco_Serial_Report.txt
    host: "{{ smtp_server }}"
    body:
  delegate_to: localhost
  run_once: true
  check_mode: false

- name: Cleanup reports
  file:
    path: /tmp/Cisco_Serial_Report.txt
    state: absent
  delegate_to: localhost
  run_once: true
  check_mode: false
