---
# tasks file for serial_report

- name: Gather device information
  ios_facts:
    gather_subset: min
  register: ios_facts
  when: ping_result.rc == 0

- name: Generate txt report file
  template:
    src: templates/txt_report_template.j2
    dest: /tmp/Cisco_Serial_Report.txt
  when: report_format == 'txt'
  delegate_to: localhost
  run_once: True
  check_mode: False

- name: Generate csv report file
  template:
    src: templates/csv_report_template.j2
    dest: /tmp/Cisco_Serial_Report.txt
  when: report_format == 'csv'
  delegate_to: localhost
  run_once: True
  check_mode: False

- name: Email Serial Number Report
  mail:
    from: "{{ from_email }}"
    to: "{{ email_address }}"
    subject: Serial Number Report for "{{ lookup('pipe','date +%Y-%m-%d') }}"
    subtype: html
    attach: /tmp/Cisco_Serial_Report.txt
    host: "{{ smtp_server }}"
    body:
  delegate_to: localhost
  run_once: True
  check_mode: False
